steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/YOUR_PROJECT_ID/flask-backend-ar/flask-app:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/YOUR_PROJECT_ID/flask-backend-ar/flask-app:latest']

  # Step 3: SSH into the Compute Engine instance and update deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'flask-instance' # Replace with your VM name
      - '--zone=us-east1-b' # Replace with your VM zone
      - '--command'
      - |
        sudo docker pull us-east1-docker.pkg.dev/YOUR_PROJECT_ID/flask-backend-ar/flask-app:latest
        sudo docker stop flask-container || true
        sudo docker rm flask-container || true
        sudo docker run -d -p 80:5000 --name flask-container us-east1-docker.pkg.dev/YOUR_PROJECT_ID/flask-backend-ar/flask-app:latest

images:
  - 'us-east1-docker.pkg.dev/YOUR_PROJECT_ID/flask-backend-ar/flask-app:latest'

timeout: '600s'

options:
  logsBucket: 'gs://cd-assign2-bucket' # Replace with your bucket name
