steps:
  # Step 1: Build the Docker image for the updated Flask app
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Build'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Push'
    args: ['push', 'us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest']

  # Step 3: SSH into the existing Compute Engine instance and update the Flask app Docker container
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Compute Engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /root/.ssh
        gcloud secrets versions access latest --secret=your-ssh-private-key > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        gcloud compute ssh flask-instance --zone=us-east1-b --ssh-key-file=/root/.ssh/id_rsa --command="
          echo 'SSH connected to the instance'
          sudo docker pull us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest
          sudo docker stop flask-container || true
          sudo docker rm flask-container || true
          sudo docker run -d -p 80:5000 --name flask-container us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest
        "
options:
   logging: CLOUD_LOGGING_ONLY