steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['compute', 'ssh', 'flask-instance', '--zone=us-east1-b', '--command', 'docker pull us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest && docker stop $(docker ps -q) && docker rm $(docker ps -a -q) && docker run -d -p 8080:5000 us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest']
images:
- 'us-east1-docker.pkg.dev/upadhayay-assign2/flask-backend-ar/flask-app:latest'
